# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all routes to index.html (important for React Router / SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
